### ISSUE TITLE
Compiling files in sub-folders

### ISSUE THREAD

**Issue by tjawa** [leobia/JsGradleCompiler#1]
@leobia I tried this plugin, but didn't find a way to compile the files in the sub-folders of the the path specified. Would love to have that feature. :)

**Comment by leobia** [comment]
Hi @tjawa , no problem with that. I'll include this feature in the next release 😃

**Comment by tjawa** [comment]
Really appreciated. 😀
Do you have any release date for that?

**Comment by leobia** [comment]
I'll start to work on this in a couple of hours. So I think for tomorrow or saturday it should be ready

**Comment by tjawa** [comment]
Thanks for your proactive replies.

I think I can help you in pacing up a little bit as I have a little look at the code and to me it seems like some code in JSComiler.java can be used in a recursive manner to achieve this. Please have a look. :)

[sampleCode.txt](https://github.com/leobia/JsGradleCompiler/files/4696285/sampleCode.txt)

**Comment by tjawa** [comment]
Wow. Thanks Man. 😀😃🙂
